//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by UXML Generator
//     version 0.0.1
//     from ScriptGenerator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Editor.Utilities;
using Editor;
using System.Reflection;
using UnityEditor;
using UnityEngine;
using UnityEditor.UIElements;
using UnityEngine.UIElements;

[CustomEditor(typeof(MyClass))]
public class @MyClassCustomInspector : UnityEditor.Editor
{
    private List<CustomBindingData> savedBindings;

    public override VisualElement CreateInspectorGUI()
    {
        var MyClassInstance= (MyClass)target;

        // Create a new VisualElement to be the root of our inspector UI
        VisualElement myInspector = new VisualElement();
        myInspector.Add(new Label("This is a custom inspector"));
        // Load and clone a visual tree from UXML
        VisualTreeAsset visualTree = AssetDatabase.LoadAssetAtPath<VisualTreeAsset>("Assets/Editor/Custom Inspectors/MyClass/MyClassUXML.uxml");
        visualTree.CloneTree(myInspector);

        //----------------------------------------------------------//
        //Button Attribute Calls
        //----------------------------------------------------------//

        var classType = MyClassInstance.GetType();

        //DisableInEditorButton Action Callback
        var DisableInEditorButtonMethod = classType.GetMethod("DisableInEditorButton", BindingFlags.NonPublic | BindingFlags.Instance);
        myInspector.Q<UnityEngine.UIElements.Button>("DisableInEditorButton").clickable.clicked += () =>
        {
            DisableInEditorButtonMethod.Invoke(MyClassInstance, default);
        };

        //TestButton2 Action Callback
        var TestButton2Method = classType.GetMethod("TestButton2", BindingFlags.NonPublic | BindingFlags.Instance);
        myInspector.Q<UnityEngine.UIElements.Button>("TestButton2").clickable.clicked += () =>
        {
            TestButton2Method.Invoke(MyClassInstance, default);
        };


        //----------------------------------------------------------//
        //Custom Label Bindings
        //----------------------------------------------------------//

        savedBindings = new List<CustomBindingData>();
        VisualElement savedElement;
        MemberInfo savedMemberInfo;

        myInspector.RegisterCallback<UnityEngine.UIElements.KeyUpEvent>(new EventCallback<KeyUpEvent>(OnKeyUpEvent));

        savedElement = myInspector.Q<GroupBox>("TitleGroup1").Q<Label>(null, GroupBox.labelUssClassName);
        savedMemberInfo = classType.GetFirstMember("MyTest1");
        savedBindings.Add(new CustomBindingData(savedElement, savedMemberInfo, default));

        savedElement = myInspector.Q<GroupBox>("TitleGroup2").Q<Label>(null, GroupBox.labelUssClassName);
        savedMemberInfo = classType.GetFirstMember("MyTest2");
        savedBindings.Add(new CustomBindingData(savedElement, savedMemberInfo, default));

        savedElement = myInspector.Q<GroupBox>("TitleGroup3").Q<Label>(null, GroupBox.labelUssClassName);
        savedMemberInfo = classType.GetFirstMember("MyTest3");
        savedBindings.Add(new CustomBindingData(savedElement, savedMemberInfo, default));

        //Force Update the Labels once all connected
        OnKeyUpEvent(default);

        //----------------------------------------------------------//

        //<GroupBox>[Dynamic Group] BIND TO -> myDynamicLabel
        myInspector.Q<GroupBox>("Dynamic Group")
        	.Q<Label>(null, GroupBox.labelUssClassName).bindingPath = "myDynamicLabel";

        //<FloatField>[m_MyFloat] BIND TO -> myDynamicLabel
        myInspector.Q<FloatField>("m_MyFloat")
        	.Q<Label>(null, FloatField.labelUssClassName).bindingPath = "myDynamicLabel";

        //<Foldout>[FoldoutGroup] BIND TO -> myDynamicLabel
        myInspector.Q<Foldout>("FoldoutGroup")
        	.Q<Label>(null, Foldout.textUssClassName).bindingPath = "myDynamicLabel";


        //----------------------------------------------------------//
        //Conditional Editors
        //----------------------------------------------------------//

        var applicationIsPlaying = Application.isPlaying;

        //Disable in Editor
        SetEnabled(myInspector.Q<Button>("DisableInEditorButton"), applicationIsPlaying, true);

        SetEnabled(myInspector.Q<LongField>("myLong"), applicationIsPlaying, true);

        //Disable in Play mode
        SetEnabled(myInspector.Q<Vector2Field>("myV2"), applicationIsPlaying, false);

        SetEnabled(myInspector.Q<Vector3Field>("myV3"), applicationIsPlaying, false);

        //----------------------------------------------------------//

        // Return the finished inspector UI
        return myInspector;
    }

    private void SetEnabled(in VisualElement visualElement, in bool playState, in bool desiredState)
    {
        var setState = playState == desiredState;

        visualElement.focusable = setState;
        visualElement.SetEnabled(setState);

        if(setState == false)
            visualElement.AddToClassList("read-only");
        else
            visualElement.RemoveFromClassList("read-only");
    }

    private void OnKeyUpEvent(KeyUpEvent evt)
    {
        var MyClassInstance = (MyClass)target;

        foreach (var bindingData in savedBindings)
        {
            var newValue = bindingData.MemberInfo.GetValue(MyClassInstance);

            if (bindingData.RequiresUpdate(newValue) == false)
            	continue;

            switch (bindingData.SavedElement)
            {
                case Label label:
                	label.text = (string)newValue;
                	break;
                default:
                	throw new NotImplementedException($"{bindingData.SavedElement.GetType().Name} not yet supported");
            }
        }
    }

}
